name: Deploy Torrent Downloader with own file server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_IP: "13.238.117.57"
      USERNAME: "ubuntu"
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: deploy Torrent Downloader
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.INSTANCE_IP }}
        username: ${{ env.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /home/ubuntu/TorDownload && cd /home/ubuntu/TorDownload
          sudo rm -rf Private-Torrent-Downlaoder-using-FileBrowser
          git clone https://${{ env.GITHUB_USERNAME }}:${{ env.GITHUB_TOKEN }}@github.com/pasinduljay/Private-Torrent-Downlaoder-using-FileBrowser.git
          cd Private-Torrent-Downlaoder-using-FileBrowser
          
          # Build and deploy the Docker containers
          bash <(curl -Ls https://gist.githubusercontent.com/pasinduljay/02cf2effb83c771c6f302b2ba59faf74/raw/8f1a8903b11da98510bb53f452fd8a0b35f04c53/Verification%2520for%2520Docker%2520and%2520Docker-compose)
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up -d